environment: production
title: "Delirium"

defaults:
  -
    scope:
      path: "_posts/"
      type: "posts"
    values:
      layout: "posts"
      permalink: "/blog/:title"
      thumb: 
        src: "/assets/images/thumb-missing.webp"
        height: "500"
        width: "500"

url: "https://state-of-delirium.github.io"
baseurl: ""

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-target-blank
  - jekyll-minifier
  - nokogiri

feed:
  icon: "/assets/images/favicon.svg"
  logo: "/assets/images/favicon.svg"

target-blank:
  add_css_classes: external-link

sass:
  style: compressed

jekyll-minifier:
  exclude: 
    - "feed.xml"
    - "*.css"

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge